import {
  Activity,
  AlarmClock,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Bell,
  BellRing,
  Blocks,
  Brain,
  ChartLine,
  Clapperboard,
  Coins,
  DoorOpen,
  FileText,
  Gavel,
  Hand,
  Hash,
  Image as ImageIcon,
  Inbox,
  ClipboardList,
  FilePlus2,
  LayoutDashboard,
  LayoutPanelTop,
  LifeBuoy,
  Tag,
  Lightbulb,
  Link2,
  Lock,
  Mail,
  Map as MapIcon,
  Megaphone,
  MessageCircleQuestion,
  MessagesSquare,
  Mic,
  Music,
  Palette,
  Puzzle,
  Quote,
  Radio,
  ScrollText,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Swords,
  TicketCheck,
  Trophy,
  UserCog,
  UserMinus,
  Users,
  Volume2,
  Vote,
  Wand2,
  Zap,
  AlertTriangle,
  AtSign,
  Bot,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CaseUpper,
  Clock,
  CornerDownRight,
  CornerRightDown,
  Crown,
  Dices,
  DoorClosed,
  Equal,
  Eraser,
  ExternalLink,
  Flame,
  Gauge,
  Gift,
  GitBranch,
  GraduationCap,
  History,
  Hourglass,
  KeyRound,
  Link as LinkIcon,
  MessageSquare,
  MessageSquareHeart,
  MessageSquareReply,
  MicOff,
  Moon,
  MousePointerClick,
  MoveRight,
  OctagonX,
  Paperclip,
  PartyPopper,
  PencilLine,
  PhoneOff,
  Pin,
  PinOff,
  Plus,
  Regex,
  Reply,
  RotateCcw,
  Ruler,
  Search,
  Shield,
  ShieldMinus,
  ShieldPlus,
  Signature,
  SmilePlus,
  StickyNote,
  TerminalSquare,
  ThumbsUp,
  Ticket,
  TicketX,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  Trash2,
  TrendingUp,
  Unlink,
  User,
  UserPlus,
  Cpu,
  Power,
  type LucideIcon,
} from "lucide-react";

/**
 * Explicit icon registry.
 *
 * Module schemas name their icon as a string, which normally means either a
 * dynamic import per icon or `import * as Icons`, and the latter pulls the
 * whole ~1500-icon library into the bundle. Naming them here keeps the imports
 * static and tree-shakeable, and an unknown name degrades to a neutral glyph
 * rather than crashing a page.
 *
 * That graceful fallback has a cost worth knowing about: a name missing from
 * here fails *silently*, and the first version of the automations section
 * shipped with every trigger, check and step showing the same puzzle piece.
 * `tests/check-icons.mjs` now asserts that every icon named in a schema is
 * registered, because a screen full of identical glyphs is not something a
 * type error will ever catch.
 */
const REGISTRY: Record<string, LucideIcon> = {
  Activity,
  AlarmClock,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Bell,
  BellRing,
  Blocks,
  Brain,
  ChartLine,
  Clapperboard,
  Coins,
  DoorOpen,
  FileText,
  Gavel,
  Hand,
  Hash,
  Image: ImageIcon,
  Inbox,
  ClipboardList,
  FilePlus2,
  LayoutDashboard,
  LayoutPanelTop,
  LifeBuoy,
  Tag,
  Lightbulb,
  Link2,
  Lock,
  Mail,
  Map: MapIcon,
  Megaphone,
  MessageCircleQuestion,
  MessagesSquare,
  Mic,
  Music,
  Palette,
  Puzzle,
  Quote,
  Radio,
  ScrollText,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Swords,
  TicketCheck,
  Trophy,
  UserCog,
  UserMinus,
  Users,
  Volume2,
  Vote,
  Wand2,
  Zap,
  AlertTriangle,
  AtSign,
  Bot,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CaseUpper,
  Clock,
  CornerDownRight,
  CornerRightDown,
  Crown,
  Dices,
  DoorClosed,
  Equal,
  Eraser,
  ExternalLink,
  Flame,
  Gauge,
  Gift,
  GitBranch,
  GraduationCap,
  History,
  Hourglass,
  KeyRound,
  Link: LinkIcon,
  MessageSquare,
  MessageSquareHeart,
  MessageSquareReply,
  MicOff,
  Moon,
  MousePointerClick,
  MoveRight,
  OctagonX,
  Paperclip,
  PartyPopper,
  PencilLine,
  PhoneOff,
  Pin,
  PinOff,
  Plus,
  Regex,
  Reply,
  RotateCcw,
  Ruler,
  Search,
  Shield,
  ShieldMinus,
  ShieldPlus,
  Signature,
  SmilePlus,
  StickyNote,
  TerminalSquare,
  ThumbsUp,
  Ticket,
  TicketX,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  Trash2,
  TrendingUp,
  Unlink,
  User,
  UserPlus,
  Cpu,
  Power,
};

export function resolveIcon(name: string): LucideIcon {
  return REGISTRY[name] ?? Puzzle;
}

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Resolved = resolveIcon(name);
  return <Resolved className={className} strokeWidth={strokeWidth} aria-hidden />;
}
